### ISSUE TITLE
When editing revo_kart.brsar, crashes without error

### ISSUE THREAD

**Issue by nanogram** [soopercool101/BrawlCrate-deprecated#19]
trying to edit mariokart wii racing sound effects. replacing sound files with custom ones
im able to modify some sfx files, but getting crash without error when replacing wav files specifically.
brawlbox has this error too.

**Comment by fancythedeveloper** [comment]
You can't edit the wav files directly. You need to edit them. Search up a tutorial on BRSAR editing. Also, BrawlCrate is for making/editing SSBB stages.

**Comment by nanogram** [comment]
I have spent over a week searching for how to edit brsar files, and brawlbox/crate are the only viable options.

**Comment by soopercool101** [comment]
To clarify fancymelonub's statement, BrawlCrate is very much Brawl-centric (though not just stages). I will look into the bug and see if there is an easy fix, however

**Comment by fancythedeveloper** [comment]
@nanogram Try asking in the MK Modding/Hacking Discord.

**Comment by nanogram** [comment]
I found a MK modding discord, but they all use brawlbox too, and no one is sure why I'm getting these crashes...
Idk if I just don't have certain files required to run this program or what, but I'm surprised that it works fine for everybody else...

**Comment by fancythedeveloper** [comment]
It's because they edit the "wavs" that are in the BRSAR, not replace them.
Try asking how to edit them and they'll answer you.

**Comment by Roadhog360** [comment]
I'm a bit late but try the 'Change Sound' option instead of the 'Replace' option.

**Comment by soopercool101** [comment]
Should be fixed due to a variety of changes. Closing now.
