### ISSUE TITLE
Include some changes from the newer versions of BrawlBox

### ISSUE THREAD

**Issue by libertyernie** [soopercool101/BrawlCrate-deprecated#3]
Versions of BrawlBox newer than 0.77 have some fixes and new features (both mine and other people's.)

I'd like to use StageBox's BrawlLib in future versions of the ["manager" apps](https://github.com/libertyernie/BrawlManagers/), since it's more actively maintained. There are a couple of changes in particular that I'd like to see included first, though, mainly relating to audio playback and RSTM encoding.

I can submit a pull request to merge in just these changes, or I can submit one to merge everything in BrawlBox's current master branch (except for the BrawlBox plugin architecture that uses IronPython - I can't seem to get NuGet working right anyway.) Let me know if you'd prefer one or the other.

**Comment by soopercool101** [comment]
I'd prefer just the changes you think are most important. 0.78 had quite a few issues with stages that caused me to fork from 0.77 in the first place, so I'd rather be able to test each change as they come than merge in the entire branch.

**Comment by libertyernie** [comment]
OK. I'll make a pull request later with just audio-related changes.

**Comment by soopercool101** [comment]
Pull requests have been merged in. Closing for now.
