### ISSUE TITLE
StageBox Animation Problem.

### ISSUE THREAD

**Issue by Lilothestitch16** [soopercool101/BrawlCrate-deprecated#9]
I have a problem with some of the animations I imported from Maya. Giratina's bones get messed up at the loop frame of the fadeout animation. The same thing happens to Cresselia, & Rayquaza. Is there a way to fix this? 
![n4yztfr - imgur](https://user-images.githubusercontent.com/8963276/43300116-6b0772ce-912b-11e8-815d-7bb39d383357.jpg)
![mlzylve - imgur](https://user-images.githubusercontent.com/8963276/43300118-6df6b814-912b-11e8-98b4-649ecfa3de9a.jpg)
![x4dexjb - imgur](https://user-images.githubusercontent.com/8963276/43300120-7042fe34-912b-11e8-9ef8-8361d669c12d.jpg)
![nut1xlk - imgur](https://user-images.githubusercontent.com/8963276/43300122-7269f410-912b-11e8-83a2-381437a0aa33.jpg)
![hbikora - imgur](https://user-images.githubusercontent.com/8963276/43300125-741852d4-912b-11e8-95cf-ba5ccf0fb859.jpg)
![stagebox_2018-07-26_22-22-13](https://user-images.githubusercontent.com/8963276/43300135-7c873c96-912b-11e8-9ec2-5df438e137b8.png)

**Comment by soopercool101** [comment]
Brawl issue with specific non-looping animations that are looped by the module. Likely not fixable for the editor

**Comment by Lilothestitch16** [comment]
I thought there was a way to fix it. Could it have been the .anim importer that caused it?

**Comment by soopercool101** [comment]
It can likely be fixed manually but I don't believe there is a way to make the editor automatically detect, view, or fix this issue. It's unfortunately out of scope for the project as of right now.

**Comment by Lilothestitch16** [comment]
R.I.P I'll have to wait a while until we figure something out.
